version: "3.7"

services:
  ruoc-loc:
    container_name: ruoc-loc-0.0.0-$NODE_ENV
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "$GRAPHQL_PORT:$GRAPHQL_PORT"
    env_file: .env
    restart: always
